/**
 * Constantes específicas para el flujo de creación de reportes.
 * Fuente única de verdad para categorías, incidentes, áreas, iconos, imágenes y descripciones.
 */
export const AREAS_POR_PLANTA = {
  KAPPA: [
    'ACABADO',
    'ADMINISTRACION',
    'ADORNO',
    'ALMACEN MP',
    'ALMACEN PIEL',
    'AREAS COMUNES',
    'AVIOS',
    'BETA 7',
    'CAPITAL HUMANO',
    'CHAMARRAS',
    'CINTOS',
    'CORTE',
    'DESARROLLO',
    'DISEÑO',
    'LASER',
    'MAQUILA',
    'MONTADO',
    'PESPUNTE',
    'PRELIMINARES',
    'PREMONTADO',
    'SALON',
    'TALLER',
    'TRAFICO'
  ],
  SIGMA: [
    'AREAS COMUNES',
    'PRELIMINARES',
    'LASER',
    'BORDADO'
  ],
  OMEGA: ['ALMACEN DE PT', 'PT OMEGA'],
  LAMBDA: [
    'AREAS COMUNES',
    'BILLETERAS',
    'BOLSAS',
    'TORRE 1'
  ],
  GENERAL: ['PATIO', 'ESTACIONAMIENTO', 'COMEDOR', 'OFICINAS'],
};

export const LISTA_AREAS_TODAS = [...new Set(Object.values(AREAS_POR_PLANTA).flat())].sort();

export const CATEGORIAS_REPORTE = [
  {
    id: 'MAQUINARIA',
    nombre: 'Maquinaria y Climatización',
    icon: 'precision_manufacturing',
    imagen: '/img/escaneo-qr.webp',
    descripcion: 'Equipos de producción, aire acondicionado y ventilación.',
    ayuda: 'Selecciona la falla y busca el código del equipo para vincular automáticamente su ubicación.',
    incidentes: [
      {
        id: 'MAQ_NO_ENCIENDE',
        nombre: 'No enciende',
        descripcion: 'El equipo no responde al intentar arrancarlo.',
        icon: 'power_settings_new',
        titulo: 'La máquina no enciende',
        prioridad: 'ALTA',
        permiteTituloPersonalizado: false,
      },
      {
        id: 'MAQ_PARO_INESPERADO',
        nombre: 'Paro inesperado',
        descripcion: 'El equipo se detuvo abruptamente durante el proceso.',
        icon: 'error_outline',
        titulo: 'Paro inesperado de máquina',
        prioridad: 'ALTA',
        permiteTituloPersonalizado: false,
      },
      {
        id: 'MAQ_ATASCO',
        nombre: 'Atasco o bloqueo',
        descripcion: 'Obstrucción o traba en mecanismo o cinta.',
        icon: 'pan_tool',
        titulo: 'Atasco o bloqueo en máquina',
        prioridad: 'MEDIA',
        permiteTituloPersonalizado: false,
      },
      {
        id: 'MAQ_RUIDO_ANORMAL',
        nombre: 'Ruido o vibración anormal',
        descripcion: 'Sonidos extraños o vibraciones intensas al operar.',
        icon: 'volume_up',
        titulo: 'Ruido o vibración anormal',
        prioridad: 'MEDIA',
        permiteTituloPersonalizado: false,
      },
      {
        id: 'MAQ_FUGA',
        nombre: 'Fuga de aceite, aire o líquido',
        descripcion: 'Pérdida de fluido o presión en mangueras/sellos.',
        icon: 'water_drop',
        titulo: 'Fuga en máquina',
        prioridad: 'MEDIA',
        permiteTituloPersonalizado: false,
      },
      {
        id: 'MAQ_SENSOR_ERROR',
        nombre: 'Sensor, alarma o pantalla con error',
        descripcion: 'Código de falla o lectura errónea en HMI/panel.',
        icon: 'warning',
        titulo: 'Falla en sensor o pantalla',
        prioridad: 'MEDIA',
        permiteTituloPersonalizado: false,
      },
      {
        id: 'AC_NO_ENFRIA',
        nombre: 'Aire acondicionado no enfría',
        descripcion: 'Sopla aire tibio o sin refrigeración.',
        icon: 'ac_unit',
        titulo: 'AC no enfría',
        prioridad: 'ALTA',
        permiteTituloPersonalizado: false,
      },
      {
        id: 'AC_NO_ENCIENDE',
        nombre: 'Clima no enciende',
        descripcion: 'Sin respuesta a control remoto o termostato.',
        icon: 'power_off',
        titulo: 'Clima sin encender',
        prioridad: 'MEDIA',
        permiteTituloPersonalizado: false,
      },
      {
        id: 'EXTRACTOR_FALLA',
        nombre: 'Extractor o ventilador con falla',
        descripcion: 'Vane trabada o motor ruidoso.',
        icon: 'mode_fan',
        titulo: 'Falla en extractor de aire',
        prioridad: 'MEDIA',
        permiteTituloPersonalizado: false,
      },
      {
        id: 'FUGA_REFRIGERANTE',
        nombre: 'Fuga de agua o refrigerante',
        descripcion: 'Goteo interior de agua o hielo visible.',
        icon: 'water_drop',
        titulo: 'Fuga de agua en equipo de clima',
        prioridad: 'ALTA',
        permiteTituloPersonalizado: false,
      },
      {
        id: 'OTRO',
        nombre: 'Otro problema de maquinaria o clima',
        descripcion: 'La falla no aparece entre las opciones disponibles.',
        icon: 'more_horiz',
        titulo: '',
        prioridad: 'MEDIA',
        permiteTituloPersonalizado: true,
      },
    ],
  },
  {
    id: 'INFRAESTRUCTURA',
    nombre: 'Infraestructura',
    icon: 'domain',
    imagen: '/img/escaneo-qr.webp',
    descripcion: 'Pisos, muros, techos e instalaciones.',
    ayuda: 'Indica el área y describe el problema en pisos, muros, techos o instalaciones fijas.',
    incidentes: [
      {
        id: 'PISO_DANADO',
        nombre: 'Piso dañado o deteriorado',
        descripcion: 'Baches, grietas o piezas sueltas en piso.',
        icon: 'grid_view',
        titulo: 'Piso dañado',
        prioridad: 'MEDIA',
        permiteTituloPersonalizado: false,
      },
      {
        id: 'TECHO_FUGA',
        nombre: 'Fuga o filtración en techo',
        descripcion: 'Goteras o humedad en láminas o losa.',
        icon: 'opacity',
        titulo: 'Filtración en techo',
        prioridad: 'ALTA',
        permiteTituloPersonalizado: false,
      },
      {
        id: 'PARED_DANADA',
        nombre: 'Pared o muro dañado',
        descripcion: 'Fisuras, desprendimiento de pintura o impacto.',
        icon: 'format_paint',
        titulo: 'Daño en pared o muro',
        prioridad: 'BAJA',
        permiteTituloPersonalizado: false,
      },
      {
        id: 'PUERTA_VENTANA',
        nombre: 'Puerta o ventana con falla',
        descripcion: 'Chapa trabada, cristal roto o descuadre.',
        icon: 'door_front',
        titulo: 'Falla en puerta o ventana',
        prioridad: 'BAJA',
        permiteTituloPersonalizado: false,
      },
      {
        id: 'OTRO',
        nombre: 'Otro problema',
        descripcion: 'La falla no aparece en la lista.',
        icon: 'more_horiz',
        titulo: '',
        prioridad: 'MEDIA',
        permiteTituloPersonalizado: true,
      },
    ],
  },
  {
    id: 'MOBILIARIO',
    nombre: 'Mobiliario',
    icon: 'chair',
    imagen: '/img/escaneo-qr.webp',
    descripcion: 'Sillas, mesas, estantes y mobiliario.',
    ayuda: 'Describe el mueble afectado, el daño presentado y su ubicación en la planta.',
    incidentes: [
      {
        id: 'SILLA_ROTA',
        nombre: 'Silla rota o en mal estado',
        descripcion: 'Pistón flojo, rueda quebrada o respaldo suelto.',
        icon: 'event_seat',
        titulo: 'Silla rota o en mal estado',
        prioridad: 'BAJA',
        permiteTituloPersonalizado: false,
      },
      {
        id: 'MESA_DANADA',
        nombre: 'Mesa o escritorio dañado',
        descripcion: 'Patas tambaleantes o cubierta fracturada.',
        icon: 'table_restaurant',
        titulo: 'Mesa o escritorio dañado',
        prioridad: 'BAJA',
        permiteTituloPersonalizado: false,
      },
      {
        id: 'ESTANTE_LOCKER',
        nombre: 'Estante o locker con falla',
        descripcion: 'Cerradura vencida o repisa vencida.',
        icon: 'inventory_2',
        titulo: 'Falla en estante o locker',
        prioridad: 'BAJA',
        permiteTituloPersonalizado: false,
      },
      {
        id: 'OTRO',
        nombre: 'Otro problema de mobiliario',
        descripcion: 'Incidencia no contemplada en las opciones.',
        icon: 'more_horiz',
        titulo: '',
        prioridad: 'MEDIA',
        permiteTituloPersonalizado: true,
      },
    ],
  },
  {
    id: 'ELECTRICO',
    nombre: 'Eléctrico e Iluminación',
    icon: 'electric_bolt',
    imagen: '/img/escaneo-qr.webp',
    descripcion: 'Contactos, lámparas y fallas eléctricas.',
    ayuda: 'Especifica la lámpara, contacto o interruptor averiado y su ubicación exacta.',
    incidentes: [
      {
        id: 'LAMPARA_FUNDIDA',
        nombre: 'Lámpara o luminaria fundida',
        descripcion: 'Foco o gabinete LED parpadeando o sin luz.',
        icon: 'lightbulb',
        titulo: 'Lámpara o luminaria fundida',
        prioridad: 'BAJA',
        permiteTituloPersonalizado: false,
      },
      {
        id: 'CONTACTO_SIN_LUZ',
        nombre: 'Contacto o tomacorriente sin energía',
        descripcion: 'Enchufe sin corriente o sobrecalentado.',
        icon: 'power',
        titulo: 'Contacto sin corriente',
        prioridad: 'MEDIA',
        permiteTituloPersonalizado: false,
      },
      {
        id: 'CORTO_CIRCUITO',
        nombre: 'Corto circuito o chispeo',
        descripcion: 'Chispas, olor a quemado o breaker botado.',
        icon: 'flash_on',
        titulo: 'Corto circuito / Chispeo eléctrico',
        prioridad: 'ALTA',
        permiteTituloPersonalizado: false,
      },
      {
        id: 'INTERRUPTOR_FALLA',
        nombre: 'Interruptor o breaker con falla',
        descripcion: 'Apagador dañado o pastilla floja.',
        icon: 'toggle_on',
        titulo: 'Falla en interruptor o pastilla',
        prioridad: 'MEDIA',
        permiteTituloPersonalizado: false,
      },
      {
        id: 'OTRO',
        nombre: 'Otro problema eléctrico',
        descripcion: 'Falla eléctrica no especificada.',
        icon: 'more_horiz',
        titulo: '',
        prioridad: 'MEDIA',
        permiteTituloPersonalizado: true,
      },
    ],
  },

  {
    id: 'PLOMERIA',
    nombre: 'Plomería y Sanitarios',
    icon: 'water_drop',
    imagen: '/img/escaneo-qr.webp',
    descripcion: 'Fugas, tuberías, lavabos y sanitarios.',
    ayuda: 'Reporta fugas de agua, lavabos u obstrucciones de drenaje para atención urgente.',
    incidentes: [
      {
        id: 'FUGA_AGUA',
        nombre: 'Fuga de agua en tubería o llave',
        descripcion: 'Llave goteando o tubo roto.',
        icon: 'plumbing',
        titulo: 'Fuga de agua',
        prioridad: 'ALTA',
        permiteTituloPersonalizado: false,
      },
      {
        id: 'LAVABO_OBSTRUIDO',
        nombre: 'Lavabo o tarja obstruida',
        descripcion: 'El agua no fluye en coladera o cespol.',
        icon: 'soap',
        titulo: 'Lavabo obstruido',
        prioridad: 'MEDIA',
        permiteTituloPersonalizado: false,
      },
      {
        id: 'SANITARIO_FALLA',
        nombre: 'Sanitario con falla de herraje/bomba',
        descripcion: 'Se tira el agua o no descarga tanque.',
        icon: 'sanitizer',
        titulo: 'Falla en sanitario',
        prioridad: 'MEDIA',
        permiteTituloPersonalizado: false,
      },
      {
        id: 'DRENAJE_OBSTRUIDO',
        nombre: 'Drenaje o dren principal obstruido',
        descripcion: 'Retorno de líquidos o inundación.',
        icon: 'waves',
        titulo: 'Drenaje obstruido',
        prioridad: 'ALTA',
        permiteTituloPersonalizado: false,
      },
      {
        id: 'OTRO',
        nombre: 'Otro problema de plomería',
        descripcion: 'Falla de fontanería no listada.',
        icon: 'more_horiz',
        titulo: '',
        prioridad: 'MEDIA',
        permiteTituloPersonalizado: true,
      },
    ],
  },
  {
    id: 'OTRO',
    nombre: 'Otro',
    icon: 'more_horiz',
    imagen: '/img/escaneo-qr.webp',
    descripcion: 'Cualquier incidencia no clasificada.',
    ayuda: 'Describe detalladamente el requerimiento o falla que no encaje en otras categorías.',
    incidentes: [
      {
        id: 'OTRO',
        nombre: 'Otro problema general',
        descripcion: 'Describir la falla de forma personalizada.',
        icon: 'edit_note',
        titulo: '',
        prioridad: 'MEDIA',
        permiteTituloPersonalizado: true,
      },
    ],
  },
];

export default {
  CATEGORIAS_REPORTE,
  AREAS_POR_PLANTA,
  LISTA_AREAS_TODAS,
};
